services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - .env
    command: >
      sh -c "uvicorn src.api.app:app --host 0.0.0.0 --port ${API_PORT}"
